// Daily Kos commenting system. (c)2005 Kos Media LLC

var kfx={animateTransition:function(panel,displayStyle,focusField,scrollNeutral){this.el=panel;this.displayStyle=displayStyle;this.focusField=focusField;this.scrollNeutral=scrollNeutral;if(scrollNeutral){kfx.origScrollState=kos.getScrollState();if(kfx.el.parentNode.offsetHeight){kfx.origHt=kfx.el.parentNode.offsetHeight;}else{kfx.origHt=kfx.el.parentNode.clientHeight;}}
this.el.style.overflow="hidden";var panelHt;if(displayStyle==kos.DISPLAY_NONE){if(panel.offsetHeight){panelHt=panel.offsetHeight;}else{panelHt=panel.clientHeight;}
this.from=panelHt;this.to=0;this.opto=0;this.opfrom=1;}else{var oldHt;if(kfx.el.parentNode.offsetHeight){oldHt=kfx.el.parentNode.offsetHeight;}else{oldHt=kfx.el.parentNode.clientHeight;}
panel.style.visibility="hidden";panel.style.height="0px";panel.style.display=displayStyle+"";panelHt=panel.scrollHeight;if(kfx.scrollNeutral){var newHt;if(kfx.el.parentNode.offsetHeight){newHt=kfx.el.parentNode.offsetHeight;}else{newHt=kfx.el.parentNode.clientHeight;}
window.scrollBy(0,newHt-oldHt);}
this.to=panelHt;this.from=0;this.opfrom=0;this.opto=1;}
this.opnow=1;this.duration=500;this.startTime=(new Date).getTime();this.timer=setInterval("kfx.step()",13);return panelHt;},step:function(){var time=(new Date).getTime();if(time>=kfx.duration+kfx.startTime){clearInterval(kfx.timer);kfx.timer=null;kfx.now=kfx.to;kfx.opnow=kfx.opto;kfx.el.style.overflow="visible";kfx.el.style.height=kfx.now+"px";if(window.ActiveXObject){kfx.el.style.filter="alpha(opacity="+kfx.opnow*100+")";}
kfx.el.style.opacity=kfx.opnow;kfx.el.style.display=kfx.displayStyle+"";kfx.el.style.height="auto";if(kfx.scrollNeutral){var newHt;if(kfx.el.parentNode.offsetHeight){newHt=kfx.el.parentNode.offsetHeight;}else{newHt=kfx.el.parentNode.clientHeight;}
window.scrollTo(kfx.origScrollState.scrollX,kfx.origScrollState.scrollY+(newHt-kfx.origHt));kfx.scrollNeutral=null;kfx.origHt=null;kfx.origScrollState=null;}
if(kfx.focusField){kfx.focusField.focus();kfx.focusField.select();if(kfx.focusField.type=="text"){kfx.focusField.select();}}
kfx.el=null;kfx.displayStyle=null;kfx.focusField=null;}else{var Tpos=(time-kfx.startTime)/(kfx.duration);kfx.now=((-Math.cos(Tpos*Math.PI)/2)+0.5)*(kfx.to-kfx.from)+kfx.from;if(kfx.scrollNeutral){var oldHt;if(kfx.el.parentNode.offsetHeight){oldHt=kfx.el.parentNode.offsetHeight;}else{oldHt=kfx.el.parentNode.clientHeight;}
kfx.el.style.height=kfx.now+"px";if(kfx.el.parentNode.offsetHeight){newHt=kfx.el.parentNode.offsetHeight;}else{newHt=kfx.el.parentNode.clientHeight;}
window.scrollBy(0,newHt-oldHt);}else{kfx.el.style.height=kfx.now+"px";}
kfx.opnow=((-Math.cos(Tpos*Math.PI)/2)+0.5)*(kfx.opto-kfx.opfrom)+kfx.opfrom;if(kfx.opnow==1){kfx.opnow=0.9999;}
if(kfx.opnow>0&&kfx.el.style.visibility=="hidden"){kfx.el.style.visibility="visible";}
if(kfx.opnow===0){kfx.el.style.visibility="hidden";}
if(window.ActiveXObject){kfx.el.style.filter="alpha(opacity="+kfx.opnow*100+")";}
kfx.el.style.opacity=kfx.opnow;}}};var kos={CONFIRM_CANCEL_MSG:"Abandon the comment entry?",insertAfter:function(newElement,targetElement){var parent=targetElement.parentNode;if(parent.lastChild==targetElement){parent.appendChild(newElement);}else{parent.insertBefore(newElement,targetElement.nextSibling);}},returnFalse:function(evt){return false;},findPosX:function(obj){var curleft=0;if(obj.offsetParent){while(obj.offsetParent){curleft+=obj.offsetLeft;obj=obj.offsetParent;}}else if(obj.x){curleft+=obj.x;}
return curleft;},findPosY:function(obj){var curtop=0;if(obj.offsetParent){while(obj.offsetParent){curtop+=obj.offsetTop;obj=obj.offsetParent;}}else if(obj.y){curtop+=obj.y;}
return curtop;},getScrollState:function(container){var scrollY;if(window.pageYOffset){scrollY=window.pageYOffset;}else{scrollY=document.body.scrollTop;}
var scrollX;if(window.pageXOffset){scrollX=window.pageXOffset;}else{scrollX=document.body.scrollLeft;}
if(!container){container=$("comments");}
var curHeight;if(container.offsetHeight){curHeight=container.offsetHeight;}else{curHeight=container.clientHeight;}
return{scrollX:scrollX,scrollY:scrollY,height:curHeight};},DISPLAY_NONE:"none",DISPLAY_BLOCK:"block",DISPLAY_INLINE:"inline",setDisplayStyle:function(panel,displayStyle,scrollState,scrollToView,padding,focusField){if(!scrollState){scrollState=kos.getScrollState();}
var panelHt;if(panel.style.display!=displayStyle){if(!window.ActiveXObject&&!kfx.el){panelHt=kfx.animateTransition(panel,displayStyle,focusField,!scrollToView);}else{var styleToBeSet=displayStyle+"";panel.style.display=styleToBeSet;if(!scrollToView){var newScrollState=kos.getScrollState();window.scrollTo(newScrollState.scrollX,scrollState.scrollY+
(newScrollState.height-scrollState.height));}
if(focusField){focusField.focus();if(focusField.type=="text"){focusField.select();}}}}
if(scrollToView&&displayStyle!=kos.DISPLAY_NONE){newScrollState=kos.getScrollState();if(!panelHt){if(panel.offsetHeight){panelHt=panel.offsetHeight;}else{panelHt=panel.clientHeight;}}
if(!padding){padding=24;}
var winHt;if(window.innerHeight){winHt=window.innerHeight;}else{winHt=document.body.clientHeight;}
var topTarget=Math.max(kos.findPosY(panel)-padding,0);var btmTarget=topTarget+panelHt+padding+padding;if(newScrollState.scrollY>topTarget||(newScrollState.scrollY+winHt)<btmTarget){var scrollHt;if((newScrollState.scrollY+winHt)<btmTarget){scrollHt=Math.max(btmTarget-winHt,0);}else{scrollHt=topTarget;}
window.scrollTo(newScrollState.scrollX,scrollHt);}
if(false){var feedback=$("feedback");feedback.innerHTML+="\nnewScrollState.scrollY: "+
newScrollState.scrollY+" newScrollState.scrollY + winHt: "+
(newScrollState.scrollY+winHt)+" topTarget:"+topTarget+" btmTarget:"+btmTarget+" panelHt:"+panelHt+" scrollHt:"+scrollHt;}}},getChildrenByTagName:function(containingElem,tagName){tagName=tagName.toUpperCase();var children=new Array();for(var i=0;i<containingElem.childNodes.length;++i){var childNode=containingElem.childNodes[i];if(childNode.nodeType==1&&childNode.nodeName==tagName){children[children.length]=childNode;}}
return children;},setupEditorComment:function(evt){return kos.setupEditor(this,"comment");},setupEditorDiary:function(evt){return kos.setupEditor(this,"diary");},setupEditor:function(anchor,mode){var editor=$("editor");if(!editor){return true;}
var previewLi=$("editorPreview");if(!previewLi){return true;}
var commentsDiv=$("comments");var scrollState=kos.getScrollState(commentsDiv);previewLi.style.display=kos.DISPLAY_NONE+"";previewLi.parentNode.removeChild(previewLi);editor.parentNode.removeChild(editor);editor.style.display=kos.DISPLAY_NONE+"";editor.style.width=commentsDiv.style.width;if(!anchor||mode=="diary"){var commentUl=commentsDiv.getElementsByTagName("UL")[0];if(!commentUl){return true;}
if(commentUl.firstChild){commentUl.insertBefore(editor,commentUl.firstChild);commentUl.insertBefore(previewLi,commentUl.firstChild);}else{commentUl.appendChild(previewLi);commentUl.appendChild(editor);}
editor.style.marginLeft="0px";editor.replyToId="(diary)";}else{var commentBox=anchor.parentNode.parentNode.parentNode;var commentLi=commentBox.parentNode;editor.replyToId=commentLi.id.substring(1);var childUl=kos.getChildrenByTagName(commentLi,"UL")[0];if(!childUl){childUl=document.createElement("ul");var parentClass=commentLi.parentNode.className;var parentIndent=parentClass.match(/i(\d+)/)[0];var newClass=parentClass.replace(/i(\d+)/,"i"+(parseInt(parentIndent.substring(1))+1));childUl.className=newClass;commentLi.appendChild(childUl);}
if(childUl.firstChild){childUl.insertBefore(editor,childUl.firstChild);childUl.insertBefore(previewLi,childUl.firstChild);}else{childUl.appendChild(previewLi);childUl.appendChild(editor);}
var editorOffset=kos.findPosX(commentsDiv)-kos.findPosX(commentLi);editor.style.marginLeft=editorOffset+"px";}
editor.storyId=$("sid").value+"";var editorSubject=$("editorSubject");kos.setDisplayStyle(editor,kos.DISPLAY_BLOCK,scrollState,true,20,editorSubject);return false;},textile:function(s){if(!s||s.length===0){return"";}
if(navigator.userAgent.indexOf('MSIE 5.0')!=-1){return s;}
var r=" "+s;var re=new RegExp('([^\\\\])\\\\([\\-\\?\\*\\+~\\^@<>&\\[\\]\\{\\}_/])','g');var escMatch;while((escMatch=re.exec(r))!==null){var entityRef="&#"+escMatch[2].charCodeAt(0)+";";r=r.replace(re,"$1"+entityRef);}
re=new RegExp('\\\\\\\\','g');r=r.replace(re,'\\');r=r.substring(1);var qtags=[['\\?\\?','cite'],['\\+','ins'],['~','sub'],['\\^','sup'],['@','code']];for(var i=0;i<qtags.length;++i){var ttag=qtags[i][0];var htag=qtags[i][1];re=new RegExp(ttag+'\\b(.+?)\\b'+ttag,'g');r=r.replace(re,'<'+htag+'>'+'$1'+'</'+htag+'>');}
re=new RegExp('\\b_(.+?)_','g');r=r.replace(re,'<em>$1</em>');re=new RegExp('([\\s\\n]+)/\\b(.+?)/','g');r=r.replace(re,'$1<em>$2</em>');re=new RegExp('([\\s\\n]+)\\*\\b(.+?)\\*','g');r=r.replace(re,'$1<strong>$2</strong>');re=new RegExp('([\\s\\n])-\\b(.+?)-','g');r=r.replace(re,'$1<del>$2</del>');re=new RegExp('"\\b(.+?)\\(\\b(.+?)\\b\\)":([^\\s]+)','g');r=r.replace(re,'<a href="$3" title="$2">$1</a>');re=new RegExp('"\\b(.+?)\\b":([^\\s]+)','g');r=r.replace(re,'<a href="$2">$1</a>');var dkospdaUrl="http://www.dkosopedia.com/index.php/";re=new RegExp('dk\\{\\{(.+?)\\}\\}');var dksMatch;while((dksMatch=re.exec(r))!==null){var dksStr=dksMatch[1].replace(/\s+/g,"_");r=r.replace(re,'<a class="dk" href="'+dkospdaUrl+dksStr+'">$1</a>');}
re=new RegExp('\\[\\[(.*)\\]\\]');while((dksMatch=re.exec(r))!==null){dksStr=dksMatch[1].replace(/\s+/g,"_");r=r.replace(re,'<a class="dk" href="'+dkospdaUrl+dksStr+'">$1</a>');}
re=new RegExp('\\[(.*)(http://\\S*)(.*)\\]','g');r=r.replace(re,'<a href="$2">$1$3</a>');re=new RegExp('(\\s)(http://\\S*)(\\s)');while((dksMatch=re.exec(r))!==null){dksStr=dksMatch[2].length>40?dksMatch[2].substring(0,36)+"...":dksMatch[2];r=r.replace(re,'$1<a href="$2">'+dksStr+'</a>$3');}
re=new RegExp('!\\b(.+?)\\(\\b(.+?)\\b\\)!','g');r=r.replace(re,'<img src="$1" alt="$2">');re=new RegExp('!\\b(.+?)\\b!','g');r=r.replace(re,'<img src="$1">');re=new RegExp('  ','g');r=r.replace(re,' &nbsp;');re=new RegExp('\\(tm\\)','g');r=r.replace(re,'&trade;');re=new RegExp('\\(c\\)','g');r=r.replace(re,'&copy;');re=new RegExp('\\(r\\)','g');r=r.replace(re,'&reg;');var lines=r.split('\n');var endtags=['','</ul>\n','</ol>\n','</p>\n'];var listtype=0;for(i=0;i<lines.length;++i){var line=lines[i].replace(/\s*$/,'');if(line.search(/^\s*\*\s+/)!=-1){line=line.replace(/^\s*\*\s+/,'\t<li>')+'</li>';if(listtype!=1){line=endtags[listtype]+'<ul>\n'+line;listtype=1;}}else if(line.search(/^\s*#\s+/)!=-1){line=line.replace(/^\s*#\s+/,'\t<li>')+'</li>';if(listtype!=2){line=endtags[listtype]+'<ol>\n'+line;listtype=2;}}else if(line.search(/^\s*bq\.\s+/)!=-1){line=endtags[listtype]+line.replace(/^\s*bq\.\s+/,'\t<blockquote>')+'</blockquote>';listtype=0;}else if(line.search(/^\s*\d+[\.\):]\s+/)!=-1){re=new RegExp('(\\d+)[\.\):](.+)','g');line=endtags[listtype]+line.replace(re,'<ol><li value="$1">$2</li></ol>');listtype=0;}else if(line.search(/^\s*h[1|2|3|4|5|6]\.\s+/)!=-1){re=new RegExp('h([1|2|3|4|5|6])\.(.+)','g');line=endtags[listtype]+line.replace(re,'<h$1>$2</h$1>');listtype=0;}else if((line.replace(/\s/g,'').length>0)){if(listtype!=3){line=endtags[listtype]+'<p>'+line;listtype=3;}else{line='<br />'+line;}}else{if(listtype==3){lines[i-1]=lines[i-1].substring(0,lines[i-1].length-1)+endtags[listtype]+"\n";line='';listtype=0;}else if(listtype===0){line='<p>&nbsp;</p>';}}
if(line.length>0){lines[i]=line+'\n';}else{lines[i]='';}}
r=lines.join('');if(listtype){r=r+endtags[listtype];listtype=0;}
return r;},editorPreview:function(evt){var editor=$("editor");if(!editor){return true;}
var previewLi=$("editorPreview");if(!previewLi){return true;}
var scrollState=kos.getScrollState();var editorErrorMessage=$("editorErrorMessage");var editorSubject=$("editorSubject");var editorSubjectValue=editorSubject.value;if(!editorSubjectValue||editorSubjectValue.length===0){kos.setDisplayStyle(editorErrorMessage,kos.DISPLAY_BLOCK,scrollState,true,20,editorSubject);return false;}
editorSubjectValue=editorSubjectValue.replace(/\"/g,"'");var previewSubject=$("previewSubject");if(previewSubject.firstChild&&previewSubject.firstChild.nodeType==3){previewSubject.firstChild.nodeValue=editorSubjectValue;}else{previewSubject.appendChild(document.createTextNode(editorSubjectValue));}
var editorComment=$("editorComment");var editorCommentValue=editorComment.value;var textiledValue=kos.textile(editorCommentValue);var previewComment=$("previewComment");if(previewComment.innerHTML!==undefined){previewComment.innerHTML=textiledValue;}else if(previewComment.firstChild&&previewComment.firstChild.nodeType==3){previewComment.firstChild.nodeValue=textiledValue;}else{previewComment.appendChild(document.createTextNode(textiledValue));}
var previewDateValue=new Date().toLocaleString();var previewDate=$("previewDate");if(previewDate.firstChild&&previewDate.firstChild.nodeType==3){previewDate.firstChild.nodeValue=previewDateValue;}else{previewDate.appendChild(document.createTextNode(previewDateValue));}
editorSubject.onkeypress=kos.editorContentChanged;editorSubject.ondrop=editorSubject.onkeypress;editorComment.onkeypress=kos.editorContentChanged;editorComment.ondrop=editorComment.onkeypress;var editorPostButton=$("editorPostButton");if(editorPostButton){editorPostButton.disabled=false;editorPostButton.onclick=kos.editorPost;}
previewLi.disabled=false;if(window.ActiveXObject){previewLi.style.filter="alpha(opacity=100)";}
previewLi.style.opacity=1;kos.setDisplayStyle(previewLi,kos.DISPLAY_BLOCK,scrollState,true,40,editorPostButton);editorErrorMessage.style.display=kos.DISPLAY_NONE;return false;},editorPost:function(evt){var editor=$("editor");if(!editor){return true;}
var previewLi=$("editorPreview");if(!previewLi){return true;}
var scrollState=kos.getScrollState();var editorErrorMessage=$("editorErrorMessage");var editorSubject=$("editorSubject");var editorSubjectValue=editorSubject.value;if(!editorSubjectValue||editorSubjectValue.length===0){kos.setDisplayStyle(editorErrorMessage,kos.DISPLAY_BLOCK,scrollState,true,20,editorSubject);return false;}
editorSubjectValue=editorSubjectValue.replace(/\"/g,"'");var editorComment=$("editorComment");var editorCommentValue=editorComment.value;var textiledValue=kos.textile(editorCommentValue);alert("This demo isn't hooked up to the server, and won't be until Stage 3. "+"However, the following data will be posted to the server when it works:"+"\nStory ID: "+editor.storyId+"\nReply to Comment ID: "+editor.replyToId+"\nComment Subject: "+editorSubjectValue+"\nComment Text: "+textiledValue);kos.editorCleanup(editor,scrollState);return false;},editorCleanup:function(editor,scrollState){if(!scrollState){scrollState=kos.getScrollState();}
kos.setDisplayStyle(editor,kos.DISPLAY_NONE,scrollState,true,40);var previewLi=$("editorPreview");if(previewLi){kos.setDisplayStyle(previewLi,kos.DISPLAY_NONE,scrollState,true,40);}
var editorPostButton=$("editorPostButton");if(editorPostButton){editorPostButton.disabled=true;editorPostButton.onclick=null;}
var editorSubject=$("editorSubject");var editorComment=$("editorComment");editorSubject.value="";editorComment.value="";editorSubject.onkeypress=null;editorSubject.ondrop=null;editorComment.onkeypress=null;editorComment.ondrop=null;var editorLink=$("editorLink");if(editorLink){editorLink.style.display=kos.DISPLAY_NONE+"";$("editorLinkUrl").value="http://";$("editorLinkLabel").value="";}},editorContentChanged:function(evt){var editorPostButton=$("editorPostButton");if(editorPostButton){editorPostButton.disabled=true;}
var previewLi=$("editorPreview");if(previewLi&&previewLi.style.display!=kos.DISPLAY_NONE){if(window.ActiveXObject){previewLi.style.filter="alpha(opacity=40)";}
previewLi.disabled=true;previewLi.style.opacity=0.4;}
var editorSubject=$("editorSubject");editorSubject.onkeypress=null;editorSubject.ondrop=null;var editorComment=$("editorComment");editorComment.onkeypress=null;editorComment.ondrop=null;return true;},cancelEditor:function(evt){var editor=$("editor");if(!editor){return true;}
var editorSubject=$("editorSubject");var editorComment=$("editorComment");var editorSubjectValue=editorSubject.value;var editorCommentValue=editorComment.value;if((editorSubjectValue&&editorSubjectValue.length>0)||(editorCommentValue&&editorCommentValue.length>0)){if(!confirm(kos.CONFIRM_CANCEL_MSG)){return false;}}
kos.editorCleanup(editor);return false;},toggleEditorHelp:function(evt){var editorHelp=$("editorHelp");if(!editorHelp){return true;}
var newStyle=kos.DISPLAY_NONE;if(!editorHelp.style.display||editorHelp.style.display==kos.DISPLAY_NONE){newStyle=kos.DISPLAY_BLOCK;}
kos.setDisplayStyle(editorHelp,newStyle,null,false);return false;},editorHelpKey:function(evt){if(kos.isButtonPressingKey(evt)){return kos.toggleEditorHelp(evt);}
return true;},toggleEditorLinkPanel:function(evt){var editorLink=$("editorLink");if(!editorLink){return true;}
var scrollState=kos.getScrollState();var newStyle=kos.DISPLAY_NONE;var editorLinkUrl=null;if(!editorLink.style.display||editorLink.style.display==kos.DISPLAY_NONE){newStyle=kos.DISPLAY_BLOCK;var editorComment=$("editorComment");var editorLinkLabel=$("editorLinkLabel");editorLinkUrl=$("editorLinkUrl");var curStr=kos.getBrowserSelectedText()+"";if(editorComment.selectionStart!=editorComment.selectionEnd){curStr=editorComment.value.substring(editorComment.selectionStart,editorComment.selectionEnd);}else if(document.selection){curStr=document.selection.createRange().text;}
if(curStr&&typeof curStr=="String"&&curStr.indexOf("<a ")===0){var linkPieces=curStr.match(new RegExp('<a.+?href="(.+?)">(.*?)</a>'));editorLinkUrl.value=linkPieces[1];editorLinkLabel.value=linkPieces[2];}else{editorLinkLabel.value=curStr?curStr:"";}}
kos.setDisplayStyle(editorLink,newStyle,scrollState,false,24,editorLinkUrl);return false;},editorLinkKey:function(evt){if(kos.isButtonPressingKey(evt)){return kos.toggleEditorLinkPanel(evt);}
return true;},editorAddLink:function(evt){var editorComment=$("editorComment");if(!editorComment){return false;}
var linkUrl=$("editorLinkUrl").value;var linkLabel=$("editorLinkLabel").value;linkUrl=linkUrl.replace(/ /g,"%20");linkUrl=linkUrl.replace(/\s/g,"");if(!linkLabel||linkLabel.length===0){linkLabel=linkUrl+"";if(linkLabel.length>40){linkLabel=linkLabel.substring(0,36)+"...";}}
kos.insertTaggedContent(editorComment,"<a href=\""+linkUrl+"\">",linkLabel,"</a>",true);kos.toggleEditorLinkPanel();$("editorLinkUrl").value="http://";$("editorLinkLabel").value="";kos.editorContentChanged(editorComment);editorComment.focus();return false;},getBrowserSelectedText:function(){var txt="";if(window.getSelection){txt=window.getSelection();}else if(document.getSelection){txt=document.getSelection();}else if(document.selection){txt=document.selection.createRange().text;}
return txt;},insertTaggedContent:function(editorComment,startTag,contentToInsert,endTag,allowOverwrite){if(editorComment.selectionStart!==undefined){editorComment.focus();var startPos=editorComment.selectionStart;var endPos=editorComment.selectionEnd;var scrollTop=editorComment.scrollTop;var curSelection=editorComment.value.substring(startPos,endPos);if(!allowOverwrite&&curSelection&&curSelection.length>0&&curSelection.indexOf(startTag)===0){if(endTag==curSelection.substring(curSelection.length-endTag.length,curSelection.length)){editorComment.value=editorComment.value.substring(0,startPos)+
curSelection.substring(startTag.length,curSelection.length-endTag.length)+
editorComment.value.substring(endPos,editorComment.value.length);editorComment.selectionStart=startPos;editorComment.selectionEnd=endPos-(startTag.length+endTag.length);editorComment.scrollTop=scrollTop;}
return false;}
if(contentToInsert){editorComment.value=editorComment.value.substring(0,startPos)+startTag+contentToInsert+endTag+
editorComment.value.substring(endPos,editorComment.value.length);}else{editorComment.value=editorComment.value.substring(0,startPos)+startTag+curSelection+endTag+
editorComment.value.substring(endPos,editorComment.value.length);}
var contentToInsertLength=contentToInsert?contentToInsert.length:(endPos-startPos);editorComment.selectionStart=startPos;editorComment.selectionEnd=startPos+startTag.length+contentToInsertLength+endTag.length;editorComment.scrollTop=scrollTop;}else if(document.selection){var sel=document.selection.createRange();if(sel.parentElement()!=editorComment){var pos=editorComment.value.length;var m=editorComment.createTextRange();m.moveStart('character',pos);m.collapse();m.select();sel=document.selection.createRange();}else{editorComment.focus();}
if(!allowOverwrite&&sel.text&&sel.text.length>0&&sel.text.indexOf(startTag)===0){if(endTag==sel.text.substring(sel.text.length-endTag.length,sel.text.length)){sel.text=sel.text.substring(startTag.length,sel.text.length-endTag.length);}
return false;}
if(contentToInsert){sel.text=startTag+contentToInsert+endTag;}else{sel.text=startTag+sel.text+endTag;}}else{editorComment.focus();if(contentToInsert){editorComment.value+=(startTag+contentToInsert+endTag);}else{editorComment.value+=(startTag+endTag);}}
return true;},getKeyCharCode:function(evt){evt=(evt||window.event);var charCode=(evt.charCode)?evt.charCode:((evt.keyCode)?evt.keyCode:((evt.which)?evt.which:0));return charCode;},isButtonPressingKey:function(evt){var charCode=kos.getKeyCharCode(evt);return(charCode==32||charCode==13);},editorBlockquote:function(evt){var editorComment=$("editorComment");if(!editorComment){return false;}
var selectedText=kos.getBrowserSelectedText();if(selectedText.length===0){selectedText=null;}else{selectedText=selectedText+"";}
kos.insertTaggedContent(editorComment,"<blockquote>",selectedText,"</blockquote>");kos.editorContentChanged(editorComment);return false;},editorBlockquoteKey:function(evt){if(kos.isButtonPressingKey(evt)){return kos.editorBlockquote();}
return true;},editorBold:function(evt){var editorComment=$("editorComment");if(!editorComment){return false;}
var selectedText=null;kos.insertTaggedContent(editorComment,"<strong>",selectedText,"</strong>");kos.editorContentChanged(editorComment);return false;},editorBoldKey:function(evt){if(kos.isButtonPressingKey(evt)){return kos.editorBold(evt);}
return true;},editorItalic:function(evt){var editorComment=$("editorComment");if(!editorComment){return false;}
var selectedText=null;kos.insertTaggedContent(editorComment,"<em>",selectedText,"</em>");kos.editorContentChanged(editorComment);return false;},editorItalicKey:function(evt){if(kos.isButtonPressingKey(evt)){return kos.editorItalic(evt);}
return true;},editorCommentFocus:function(evt){$("editorComment").focus();return false;},rewireControls:function(){if(!document.getElementById){return false;}
if(navigator.userAgent.indexOf('MSIE 5')!=-1&&navigator.userAgent.indexOf('Mac')!=-1){return false;}
var commentsDiv=$("comments");if(!commentsDiv){return false;}
var anchors=commentsDiv.getElementsByTagName("a");var anchor;for(var i=0;i<anchors.length;++i){anchor=anchors[i];if(anchor.firstChild.nodeType==3&&anchor.parentNode.className.indexOf("cl")!=-1&&anchor.firstChild.nodeValue.indexOf("Reply")!=-1){anchor.onclick=kos.setupEditorComment;}else if(anchor.firstChild.nodeType==3&&anchor.parentNode.parentNode.className.indexOf("cbar")!=-1&&anchor.firstChild.nodeValue.indexOf("Post")!=-1){anchor.onclick=kos.setupEditorDiary;}}
var rateAllForm=$("rateAllForm");if(rateAllForm){rateAllForm.onsubmit=kos.returnFalse;}
var editorPreviewButton=$("editorPreviewButton");if(editorPreviewButton){editorPreviewButton.onclick=kos.editorPreview;}
var editorPostButton=$("editorPostButton");if(editorPostButton){editorPostButton.disabled=true;}
var editorCancelButton=$("editorCancelButton");if(editorCancelButton){editorCancelButton.onclick=kos.cancelEditor;}
var editorBlockquoteButton=$("editorBlockquote");if(editorBlockquoteButton){editorBlockquoteButton.onmousedown=kos.editorBlockquote;editorBlockquoteButton.onkeydown=kos.editorBlockquoteKey;editorBlockquoteButton.onclick=kos.editorCommentFocus;}
var editorBoldButton=$("editorBold");if(editorBoldButton){editorBoldButton.onmousedown=kos.editorBold;editorBoldButton.onkeydown=kos.editorBoldKey;editorBoldButton.onclick=kos.editorCommentFocus;}
var editorItalicButton=$("editorItalic");if(editorItalicButton){editorItalicButton.onmousedown=kos.editorItalic;editorItalicButton.onkeydown=kos.editorItalicKey;editorItalicButton.onclick=kos.editorCommentFocus;}
var editorLinkButton=$("editorLinkButton");if(editorLinkButton){editorLinkButton.onmousedown=kos.toggleEditorLinkPanel;editorLinkButton.onkeydown=kos.editorLinkKey;editorLinkButton.onclick=kos.returnFalse;}
var editorAddLinkButton=$("editorAddLink");if(editorAddLinkButton){editorAddLinkButton.onclick=kos.editorAddLink;}
var editorHelpButton=$("editorHelpButton");if(editorHelpButton){editorHelpButton.onclick=kos.toggleEditorHelp;editorHelpButton.onkeydown=kos.editorHelpKey;}
return true;},checkDOM:function(){if($("footer")&&$("editor")){init();}else{setTimeout("kos.checkDOM();",200);}}};function $(elId){return document.getElementById(elId);}
function init(){if(arguments.callee.done){return;}
arguments.callee.done=true;kos.rewireControls();}
if(document.addEventListener){document.addEventListener("DOMContentLoaded",init,null);}
if(navigator.userAgent.indexOf('Opera')!=-1||navigator.userAgent.indexOf('Safari')!=-1){kos.checkDOM();}
window.onload=init;
