// Daily Kos polling system. (c)2006 Kos Media LLC

var KOS_URL_BASE="/";var kos={DISABLED:false,REFRESH_TIMEOUT_TIME:30000,DEBUG:false,LOG:false,ANIMATE:true,URL_BASE:KOS_URL_BASE,IMAGE_BASE:"http://images.dailykos.com/images/admin/",SUBMIT_BASE:KOS_URL_BASE+"ajax/",insertAfter:function(newElement,targetElement){var parent=targetElement.parentNode;if(parent.lastChild==targetElement){parent.appendChild(newElement);}else{parent.insertBefore(newElement,targetElement.nextSibling);}},DISPLAY_NONE:"none",DISPLAY_BLOCK:"block",DISPLAY_INLINE:"inline",DISPLAY_DEFAULT:"",getChildByTagName:function(elem,tagName){tagName=tagName.toUpperCase();if(elem&&elem.childNodes){for(var i=0;i<elem.childNodes.length;++i){var childNode=elem.childNodes[i];if(childNode.nodeType==1&&childNode.nodeName==tagName){return childNode;}}}
return null;},getElementsByClassName:function(elem,className,tagName){var children=[];if(elem){var re=new RegExp('\\b'+className+'\\b');if(!tagName){tagName="*";}
var elems=elem.getElementsByTagName(tagName);for(var i=0;i<elems.length;++i){var childNode=elems[i];if(childNode.className&&childNode.className.match(re)){children[children.length]=childNode;}}}
return children;},getElementsByName:function(elem,elName,tagName){var children=[];if(elem){if(!tagName){tagName="*";}
var elems=elem.getElementsByTagName(tagName);for(var i=0;i<elems.length;++i){var childNode=elems[i];if(childNode.name&&childNode.name==elName){children[children.length]=childNode;}}}
return children;},getElementByClassName:function(elem,className,tagName){if(elem){var re=new RegExp('\\b'+className+'\\b');if(!tagName){tagName="*";}
var elems=elem.getElementsByTagName(tagName);for(var i=0;i<elems.length;++i){var childNode=elems[i];if(childNode.className&&childNode.className.match(re)){return childNode;}}}
return null;},getAncestorByClassName:function(elem,className){var re=new RegExp('\\b'+className+'\\b');while(elem&&elem.parentNode){if(elem.parentNode.className&&elem.parentNode.className.match(re)){return elem.parentNode;}
elem=elem.parentNode;}
return null;},pollChoiceChanged:function(){if(kos.mainDiv.className.indexOf("ing")>-1){return false;}
var pollDiv=kos.getAncestorByClassName(this,"poll");if(!pollDiv){return false;}
var pollSubmit=kos.getElementByClassName(pollDiv,"pollSubmit","input");if(pollSubmit){pollSubmit.disabled=false;pollSubmit.onclick=kos.submitPoll;}
return true;},submitPoll:function(evt){var pollDiv=kos.getAncestorByClassName(this,"poll");if(!pollDiv){return false;}
var opts=kos.getElementsByClassName(pollDiv,"aid","input");var aid=-1;for(var i=0;i<opts.length;++i){if(opts[i].checked){aid=i+1;var po=opts[i].id.slice(2);break;}}
if(aid<1){return false;}
var qid=kos.getElementsByName(pollDiv,"qid","input")[0].value;var ispoll=kos.getElementsByName(pollDiv,"ispoll","input")[0].value;var thissid=kos.getElementsByName(pollDiv,"sid","input")[0].value;this.disabled=true;var bbs=kos.createBusyBallSpan();kos.insertAfter(bbs,this.parentNode.firstChild);kos.addBusyBall(bbs);var bag={input:this,po:po,bbs:bbs,pollDiv:pollDiv};var params="sid="+thissid+"&qid="+qid+"&ispoll="+ispoll+"&aid="+aid;var kjaxreq=new kos.kjax(kos.finishSubmitPoll,bag,kos.SUBMIT_BASE+"poll",params,"POST");return false;},finishSubmitPoll:function(kjaxReq){this.input.disabled=false;if(kjaxReq.FAILED){kos.removeBusyBall(this.bbs,false);return false;}
kos.removeBusyBall(this.bbs,true);var pr=$("pr"+this.po);if(pr){pr.lastChild.firstChild.innerHTML=1+(pr.lastChild.firstChild.innerHTML-0);}
var pollDiv=this.pollDiv;var vtotal=kos.getElementByClassName(pollDiv,"vtotal","span");if(vtotal){var total=1+(vtotal.innerHTML-0);vtotal.innerHTML=total;}
var prs=kos.getElementsByClassName(pollDiv,"pr","tr");for(var p=0;p<prs.length;++p){var prop=prs[p].lastChild.firstChild.innerHTML/total;var pct=Math.round(prop*100)+"%";prs[p].firstChild.innerHTML=pct;var offset=-400+Math.round(prop*400);prs[p].lastChild.style.backgroundPosition=offset+"px 0px";}
kos.pollResults.apply(vtotal);var pvv=kos.getElementByClassName(pollDiv,"pvv","span");if(pvv){pvv.style.display=kos.DISPLAY_NONE;}
return true;},pollResults:function(evt){var pollDiv=kos.getAncestorByClassName(this,"poll");if(!pollDiv){return false;}
var pollForm=kos.getChildByTagName(pollDiv,"form");var prs=kos.getElementsByClassName(pollDiv,"pr","tr");var kpoll=new kos.kpoll(pollForm,prs);if(prs[0]&&prs[0].lastChild.style.backgroundPosition&&kos.ANIMATE){kpoll.startAnimation();}else if(pollForm){pollForm.className="voted";}
return false;},pollVote:function(evt){var pollDiv=kos.getAncestorByClassName(this,"poll");if(!pollDiv){return false;}
var pollForm=kos.getChildByTagName(pollDiv,"form");if(pollForm){pollForm.className="vote";if(window.ActiveXObject){var prs=kos.getElementsByClassName(pollDiv,"pr","tr");for(var p=0;p<prs.length;++p){prs[p].style.display=kos.DISPLAY_NONE;prs[p].firstChild.style.display=kos.DISPLAY_NONE;prs[p].lastChild.style.display=kos.DISPLAY_NONE;}}}
return false;},precacheImages:function(){if(document.images){log("precaching images...");kos.precache=[];kos.precache[0]=new Image(288,16);kos.precache[0].src=kos.IMAGE_BASE+"BusyBall16.gif";kos.precache[1]=new Image(800,17);kos.precache[1].src=kos.IMAGE_BASE+"Thermometer17.gif";}
return false;},createBusyBallSpan:function(feedbackText){if(!feedbackText){feedbackText="Submitting...";}
var containerSpan=document.createElement("span");containerSpan.setAttribute("class","busyBall");containerSpan.setAttribute("title","We're talking to the server."+" You don't need to wait for this to finish.");containerSpan.className="busyBall";containerSpan.innerHTML='<span class="bbi"><img src="'+kos.IMAGE_BASE+'BusyBall16.gif" width="288" height="16" /></span><span class="bbc">'+
feedbackText+'</span>';return containerSpan;},addBusyBall:function(busyBallSpan){var busyBallImg=busyBallSpan.firstChild.firstChild;if(!kos.busyBalls){kos.busyBalls=[busyBallImg];kos.busyBallOffset=0;kos.busyBallInterval=setInterval(kos.animateBusyBalls,120);}else{kos.busyBalls[kos.busyBalls.length]=busyBallImg;}},removeBusyBall:function(busyBallSpan,succeeded,removeImmediately){var busyBallImg=busyBallSpan.firstChild.firstChild;if(kos.busyBalls){var newBusyBalls=[];for(var i=0,j=0;i<kos.busyBalls.length;++i){if(kos.busyBalls[i]!=busyBallImg){newBusyBalls[j]=kos.busyBalls[i];++j;}}
if(j>0){kos.busyBalls=newBusyBalls;}else{if(kos.busyBallInterval){clearInterval(kos.busyBallInterval);delete kos.busyBallInterval;}
delete kos.busyBalls;delete kos.busyBallOffset;}}
if(removeImmediately){if(busyBallSpan.parentNode){busyBallSpan.parentNode.removeChild(busyBallSpan);}}else{var bbimg=busyBallSpan.firstChild.firstChild;var duration=2000;if(!succeeded){bbimg.style.marginLeft="-272px";busyBallSpan.lastChild.innerHTML="FAILED.";busyBallSpan.setAttribute("title","Server update failed. Check your connection, and please try again.");duration=6000;}else{bbimg.style.marginLeft="-256px";busyBallSpan.lastChild.innerHTML="Complete.";busyBallSpan.setAttribute("title","Server updated successfully.");}
setTimeout(kos.completeBusyBall.bind(busyBallSpan),duration);}},completeBusyBall:function(){var busyBallSpan=this;if(busyBallSpan.parentNode){busyBallSpan.parentNode.removeChild(busyBallSpan);}},animateBusyBalls:function(){if(kos.busyBalls){for(var i=0;i<kos.busyBalls.length;++i){kos.busyBalls[i].style.marginLeft=(kos.busyBallOffset+"px");}
kos.busyBallOffset-=16;kos.busyBallOffset%=-256;}},checkRequirements:function(){log("Checking requirements for "+navigator.userAgent);kos.DISABLED=true;if(navigator.userAgent.indexOf('MSIE 5')!=-1&&navigator.userAgent.indexOf('Mac')!=-1){return false;}
if(navigator.userAgent.indexOf('MSIE 5.0')!=-1){return false;}
if(!document.getElementsByTagName||!document.createElement){return false;}
var appleIdx=navigator.userAgent.indexOf('AppleWebKit');if(appleIdx!=-1){log("isSafari");kos.isSafari=true;var appleRev=navigator.userAgent.substring(appleIdx+12,navigator.userAgent.indexOf("(",appleIdx+12));var appleMajor=parseInt(appleRev,10);if(appleMajor<120){return false;}}else if(navigator.userAgent.indexOf('Konqueror')!=-1){log("isKonqueror");kos.isKonqueror=true;}
kos.isIE6Css=(document.compatMode&&document.compatMode.indexOf("CSS1")>=0)?true:false;log((window.ActiveXObject?"Has":"Does not have")+" window.ActiveXObject");if(window.opera){log("window.opera.version(): "+window.opera.version());if(parseInt(window.opera.version(),10)>=9){log("is Opera9 Plus");kos.isOpera9Plus=true;}}else{kos.isIE6Minus=!!window.ActiveXObject;var msieIdx=navigator.userAgent.indexOf('MSIE');if(msieIdx!=-1){var msieMajor=parseInt(navigator.userAgent.substring(msieIdx+5,msieIdx+7),10);if(msieMajor>6){kos.isIE6Css=true;kos.isIE6Minus=false;}}}
kos.DISABLED=false;log("Requirements met.");return true;},rewireControls:function(){log("Rewiring controls...");var uidField=$("uid");if(uidField){kos.uid=uidField.value;}
var unameField=$("uname");if(unameField){kos.uname=unameField.value;}
kos.mainDiv=$("main");kos.rewirePolls();kos.precacheImages();log("Rewiring complete.");return true;},rewirePolls:function(){var pollDivs=kos.getElementsByClassName(kos.mainDiv,"poll","div");for(var j=0;j<pollDivs.length;++j){var pollDiv=pollDivs[j];if(pollDiv){var pollSubmit=kos.getElementByClassName(pollDiv,"pollSubmit","input");if(pollSubmit){pollSubmit.onclick=kos.submitPoll;pollSubmit.disabled=true;}
var pollResult=kos.getElementByClassName(pollDiv,"pollResult","a");if(pollResult){pollResult.onclick=kos.pollResults;}
var pollVote=kos.getElementByClassName(pollDiv,"pollVote","a");if(pollVote){pollVote.onclick=kos.pollVote;}
var pollRs=kos.getElementsByClassName(pollDiv,"aid","input");for(var i=0;i<pollRs.length;++i){pollRs[i].checked=false;pollRs[i].onclick=kos.pollChoiceChanged;}}}},init:function(){log("in init()");if(arguments.callee.done){return;}
arguments.callee.done=true;if(!kos.DISABLED){kos.rewireControls();}},loadUnderway:true,nowFullyLoaded:function(){log("Now fully loaded. Allowing further loading...");kos.loadUnderway=false;kos.init();},checkDOM:function(){log("Checking to see if the DOM is ready for rewiring...");if(kos.DISABLED){log("Requirements NOT met.");return;}else if($("nextPage")){kos.init();}else{setTimeout(kos.checkDOM,100);}},kjaxTimeout:function(){this.onTimeout();},kjaxReady:function(){this.onReadyStateChange();},kjaxRetry:function(){this.onRetry();},READY_STATE_COMPLETE:4,kjax:function(callbackFunction,callbackContext,url,params,method,contentType){this.callbackFunction=callbackFunction;this.callbackContext=callbackContext;this.contentType=contentType;if(!this.contentType){this.contentType="application/x-www-form-urlencoded";}
this.url=url;this.params=params;this.xhr=null;if(typeof XMLHttpRequest!='undefined'){this.xhr=new XMLHttpRequest();}else if(window.ActiveXObject){this.xhr=new ActiveXObject("Microsoft.XMLHTTP");}
if(!method){this.method="GET";}else{this.method=method.toUpperCase();}
if(this.xhr){this.timeout=setTimeout(kos.kjaxTimeout.bind(this),kos.REFRESH_TIMEOUT_TIME);this.xhr.onreadystatechange=kos.kjaxReady.bind(this);if(this.xhr.overrideMimeType){this.xhr.overrideMimeType('text/xml');}
this.xhr.open(this.method,this.url,true);this.xhr.setRequestHeader("Content-Type",this.contentType);this.xhr.send(this.method=="POST"?this.params:null);}},kpoll:function(pollForm,prs){log("kpoll created");this.pollForm=pollForm;this.prs=prs;}};kos.kjax.prototype={onReadyStateChange:function(){var ready=this.xhr.readyState;if(ready==kos.READY_STATE_COMPLETE){if(this.timeout){clearTimeout(this.timeout);this.timeout=null;}
this.status=this.xhr.status;if(this.xhr.status>=400){this.FAILED=true;var debugMsg="There is a problem communicating with the server:\nresponse code: HTTP "+
this.xhr.status+" "+this.xhr.statusText;log(debugMsg);if(kos.DEBUG){alert(document.title+":\n"+debugMsg);}}
this.statusText=this.xhr.statusText;this.responseText=this.xhr.responseText;this.responseXml=this.xhr.responseXML;if(this.callbackFunction){this.callbackFunction.apply(this.callbackContext,[this]);}}},onTimeout:function(){this.xhr.abort();this.FAILED=true;log("FAILURE: kjax request to url "+this.url+" timed out, with params: "+this.params);if(this.timeout){clearTimeout(this.timeout);this.timeout=null;}
if(this.callbackFunction){this.callbackFunction.apply(this.callbackContext,[this]);}}};kos.kpoll.prototype={startAnimation:function(){for(var p=0;p<this.prs.length;++p){if(window.ActiveXObject){this.prs[p].style.display=kos.DISPLAY_BLOCK;this.prs[p].firstChild.style.display=kos.DISPLAY_BLOCK;this.prs[p].lastChild.style.display=kos.DISPLAY_BLOCK;}
var backPos=this.prs[p].lastChild.style.backgroundPosition;this.prs[p].lastChild.toPosition=backPos;this.prs[p].lastChild.toPos=backPos.match(/-?\d+px/)[0].slice(0,-2);this.prs[p].lastChild.toPos-=-400;this.prs[p].firstChild.toPct=this.prs[p].firstChild.innerHTML.slice(0,-1);this.prs[p].firstChild.innerHTML="0%";this.prs[p].firstChild.style.width="9%";this.prs[p].lastChild.style.width="91%";this.prs[p].lastChild.toCt=this.prs[p].lastChild.firstChild.innerHTML;this.prs[p].lastChild.firstChild.innerHTML="0";this.prs[p].lastChild.style.backgroundPosition="-400px 0px";}
this.pollForm.className="voted";this.from=this.now=0;this.to=1.0;this.duration=2000;this.startTime=new Date().getTime();this.timer=setInterval(this.step.bind(this),13);},step:function(){var time=new Date().getTime();if(time>=this.duration+this.startTime){clearInterval(this.timer);this.timer=null;this.now=this.to;for(var p=0;p<this.prs.length;++p){this.prs[p].lastChild.style.backgroundPosition=this.prs[p].lastChild.toPosition;this.prs[p].lastChild.firstChild.innerHTML=this.prs[p].lastChild.toCt;this.prs[p].firstChild.innerHTML=this.prs[p].firstChild.toPct+"%";}
this.prs=null;log("kpoll complete.");}else{var Tpos=(time-this.startTime)/(this.duration);this.now=((-Math.cos(Tpos*Math.PI)/2)+0.5)*(this.to-this.from)+this.from;for(p=0;p<this.prs.length;++p){var newX=(Math.round(this.now*this.prs[p].lastChild.toPos)-400);this.prs[p].lastChild.style.backgroundPosition=newX+"px 0px";this.prs[p].lastChild.firstChild.innerHTML=Math.round(this.prs[p].lastChild.toCt*this.now);this.prs[p].firstChild.innerHTML=Math.round(this.now*this.prs[p].firstChild.toPct)+"%";}}}};function $(elId){return document.getElementById(elId);}
Function.prototype.bind=function(object){var __method=this;return function(){return __method.apply(object,arguments);};};function log(msg){if(kos.LOG){if(typeof msg=="string"){var isStr=true;var d=new Date().getTime();msg=d+" "+(d-kos.logtime)+": "+msg;kos.logtime=d;}
if(navigator.userAgent.toLowerCase().indexOf("firefox")!=-1&&window.console){if(arguments.length>1){var args=[];for(var i=1;i<arguments.length;++i){args[i-1]=arguments[i];}
window.console.log(msg,args);}else{window.console.log(msg);}}else if(msg&&isStr){var feedback=$("feedback");if(!feedback){var body=document.getElementsByTagName('body')[0];if(document.body&&window.ActiveXObject){var feedhtml='<textarea id="feedback" style="width:900px;height:100px;margin:20px auto;"></textarea>';document.body.insertAdjacentHTML('afterBegin',feedhtml);}else if(body&&!window.ActiveXObject){feedback=document.createElement("textarea");feedback.id="feedback";feedback.style.width="500px";feedback.style.height="100px";feedback.style.margin="20px auto";feedback.style.clear="both";body.appendChild(feedback);}
feedback=$("feedback");}
if(feedback){if(kos.logBuffer){feedback.value+=kos.logBuffer;kos.logBuffer=null;}
feedback.value+=(msg+"\n");}else{if(!kos.logBuffer){kos.logBuffer="";}
kos.logBuffer+=(msg+"\n");document.title=msg;}}}}
log("polls.js loaded and running...");if(document.addEventListener){document.addEventListener("DOMContentLoaded",kos.init,null);}
window.onload=kos.nowFullyLoaded;